POLLS_TESTING_SEED= -1974231999
AUTHOR_ID   = KPRCA
SERVICE_ID  = 00020
CFLAGS      = -g -Werror -Wno-overlength-strings -Wno-packed -Wno-pointer-to-int-cast
POLLS_RELEASE_SEED = -423157946

include ../../make/challenge.mk
