POLLS_RELEASE_SEED= 2084761208
POLLS_TESTING_SEED= -1596191786
AUTHOR_ID  = CROMU
SERVICE_ID = 00005
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
IFLAGS     = -Iinclude
POLLS_TESTING_COUNT = 0
POLLS_RELEASE_COUNT = 1000

include ../../make/challenge.mk
