POLLS_RELEASE_SEED= 377587857
POLLS_TESTING_SEED= -591896626
AUTHOR_ID  = CROMU
SERVICE_ID = 00038
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-pointer-to-int-cast 
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude
include ../../make/challenge.mk
