AUTHOR_ID  = CROMU
SERVICE_ID = 00048
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -mstack-alignment=3 -Wno-pointer-bool-conversion
VULN_COUNT = 1
CC         = clang

include ../../make/challenge.mk
