POLLS_RELEASE_SEED= -349041664
POLLS_TESTING_SEED= 73836627
AUTHOR_ID  = CROMU
SERVICE_ID = 00036
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
IFLAGS     = -Iinclude

POLLS_RELEASE_COUNT = 50
POLLS_TESTING_COUNT = 950

include ../../make/challenge.mk
