POLLS_RELEASE_SEED= 1681795162
POLLS_TESTING_SEED= 1677617456
AUTHOR_ID  = NRFIN
SERVICE_ID = 00016
CFLAGS     = -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude
POLLS_RELEASE_COUNT = 1000

include ../../make/challenge.mk
