POLLS_RELEASE_SEED= -990494923
POLLS_TESTING_SEED= -1708909191
AUTHOR_ID  = NRFIN
SERVICE_ID = 00041
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-error=address-of-packed-member
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude

include ../../make/challenge.mk
