POLLS_RELEASE_SEED= 286462723
POLLS_TESTING_SEED= 104578085
AUTHOR_ID  = CROMU
SERVICE_ID = 00014
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude
include ../../make/challenge.mk
