POLLS_RELEASE_SEED= 1842195422
POLLS_TESTING_SEED= -1951642613
AUTHOR_ID      = CROMU
SERVICE_ID     = 00019
CFLAGS         = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
IFLAGS         = -Iinclude
LIB_IFLAGS     = -Iinclude

POLLS_RELEASE_COUNT = 300
POLLS_TESTING_COUNT = 700

include ../../make/challenge.mk
