POLLS_TESTING_SEED= 97157337
AUTHOR_ID = KPRCA
SERVICE_ID = 00040
CFLAGS = -g -O0 -Werror -Wall -Wno-unused-function -Wno-unused-variable -Wno-error=implicit-int
POLLS_RELEASE_SEED = 1029384756

include ../../make/challenge.mk
