AUTHOR_ID  = CROMU
SERVICE_ID = 00076
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-implicit-int -Wno-attributes -Wno-int-to-pointer-cast
VULN_COUNT = 1

include ../../make/challenge.mk
