POLLS_RELEASE_SEED= 1395246589
POLLS_TESTING_SEED= 507740670
AUTHOR_ID  = CROMU
SERVICE_ID = 00037
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast

include ../../make/challenge.mk
