AUTHOR_ID  = KPRCA
SERVICE_ID = 00055
CFLAGS     = -O0 -g -Wno-overlength-strings -Wno-packed -Wall -Wno-unused-variable -Wno-unused-function -Werror -Wno-error=return-type
VULN_COUNT = 1

include ../../make/challenge.mk
