POLLS_RELEASE_SEED= 1496047114
POLLS_TESTING_SEED= 596837685
AUTHOR_ID  = CROMU
SERVICE_ID = 00010
CFLAGS      = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -Wno-stringop-overflow
include ../../make/challenge.mk
