AUTHOR_ID  = NRFIN
SERVICE_ID = 00071
CC         = clang
CFLAGS     = -g -Wall -Wextra -pedantic -Werror -Wshadow -Wstrict-overflow -fpack-struct=32 -mstack-alignment=64 -mstackrealign -Wall -Wno-overlength-strings -Wno-packed -Wno-sign-compare -Wno-variadic-macros -fPIE
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude
VULN_COUNT = 1

include ../../make/challenge.mk
