POLLS_RELEASE_SEED= 546793269
POLLS_TESTING_SEED= 1324915757
AUTHOR_ID  = NRFIN
SERVICE_ID = 00039
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude

include ../../make/challenge.mk
