POLLS_RELEASE_SEED= 172223516
POLLS_TESTING_SEED= -750311787
AUTHOR_ID  = NRFIN
SERVICE_ID = 00030
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-error=address-of-packed-member
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude

include ../../make/challenge.mk
