AUTHOR_ID  = NRFIN
SERVICE_ID = 00028
CFLAGS     = -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed
LIB_IFLAGS = -Iinclude
IFLAGS     = -Iinclude
VULN_COUNT = 2

include ../../make/challenge.mk
