AUTHOR_ID  = NRFIN
SERVICE_ID = 00015

CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-error=implicit-int

POLLS_RELEASE_SEED = -1766396818
POLLS_TESTING_SEED = -908939435

include ../../make/challenge.mk
