AUTHOR_ID  = NRFIN
SERVICE_ID = 00017
POLLS_RELEASE_COUNT = 1000
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-error=implicit-int

POLLS_RELEASE_SEED = 854437448
POLLS_TESTING_SEED = 1892282553

include ../../make/challenge.mk
