AUTHOR_ID  = KPRCA
SERVICE_ID = 00086
CFLAGS     = -O1 -g -Werror -Wno-overlength-strings -Wno-packed -Wall -mstackrealign -DDISABLE_HEAP_GUARD -include src/_defines.h -Wno-error=unused-but-set-variable
VULN_COUNT = 1

include ../../make/challenge.mk
